// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5005485e-de1d-4c49-924b-c3074fb25689";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDistance1Change();
void onDistance2Change();
void onDistance3Change();
void onCarOutChange();

float distance1;
float distance2;
float distance3;
bool carOut;
bool isClose1;
bool isClose2;
bool isClose3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(distance1, READWRITE, ON_CHANGE, onDistance1Change);
  ArduinoCloud.addProperty(distance2, READWRITE, ON_CHANGE, onDistance2Change);
  ArduinoCloud.addProperty(distance3, READWRITE, ON_CHANGE, onDistance3Change);
  ArduinoCloud.addProperty(carOut, READWRITE, ON_CHANGE, onCarOutChange);
  ArduinoCloud.addProperty(isClose1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(isClose2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(isClose3, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
